apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: smartwaydepsvc
  name: smartwaydepsvc
spec:
  ports:
  - name: 80-80
    nodePort: 31000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: smartwaydep
  type: NodePort
status:
  loadBalancer: {}
