apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myconfigmapdep
  name: myconfigmapdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myconfigmapdep
  strategy: {}
  template:
    metadata:
      labels:
        app: myconfigmapdep
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        envFrom:
          - configMapRef:
              name: myconfigmap
