apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeselectortest
  name: nodeselectortest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeselectortest
  template:
    metadata:
      labels:
        app: nodeselectortest
    spec:
      containers:
      - image: httpd
        name: httpd
      nodeSelector:
        spec: highend
