apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydaemonset
  labels:
    app: mydstest
spec:
  template:
    metadata:
      name: mydaemonset
      labels:
        app: mydstest
    spec:
      containers:
        - name: mydaemonsetcontainer
          image: quay.io/fluentd_elasticsearch/fluentd:latest
          tolerations:
            - key: company
              value: thinknxy
              operator: Equal
              effect: NoSchedule
  selector:
    matchLabels:
      app: mydstest
