apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsvolpvc
  labels:
    storage: nfsstorage

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests: 
      storage: 100Mi
  selector:
    matchLabels:
      storage: nfsstorage

