apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "admin"
            name:  MONOGO_INITDB_ROOT_PASSWORD
            value: "demopassword" 
        command: [mongod, '--bind_ip_all', '--replSet',  'demors0']
        volumeMounts:
           - name: mongo-vol
             mountPath: /data/db
  serviceName: mongosvc

  volumeClaimTemplates:
    - metadata: 
        name: mongo-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nfs-client
        resources:
            requests:
              storage: 1Gi

