apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appsadep
  name: appsadep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsadep
  template:
    metadata:
      labels:
        app: appsadep
    spec:
      serviceAccountName: app-sa
      containers:
      - image: httpd:latest
        name: httpd
