apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-sa-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: saple-sa-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sample-sa-role
subjects:
- kind: ServiceAccount
  name: sample-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sampledeployment
  name: sampledeployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampledeployment
  template:
    metadata:
      labels:
        app: sampledeployment
    spec:
      serviceAccountName: sample-sa
      containers:
      - image: httpd:latest
        name: httpd
